handle: ascmSepaPaypal
isFrontendEnabled: '1'
name: 'ASCM SEPA PayPal'
paymentType: purchase
settings:
  _brandName: ''
  brandName: ''
  clientId: AcCQjLTvL9sHHWD4ZSq7P49rVe-ZM6uYyhDIJKdaqMz_H-lkqKPil1kG5oQp-FRm479ar4w72Td2cDdq
  landingPage: BILLING
  secret: EIOeO1wQP111ajHc6pldvXG46Ax2mZrnjzzwb7B59sJxpeksxAeivLEPqTWQWe36YV-JvqfDOBncnQyY
  sendCartInfo: '1'
  sendShippingInfo: '0'
  testMode: '0'
sortOrder: 99
type: craft\commerce\paypalcheckout\gateways\Gateway
