handle: stripe
isFrontendEnabled: '1'
name: Stripe
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: purchase
settings:
  apiKey: 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
  publishableKey: pk_live_51PY7jIF8okohzcqHsRsMngyZo7XzvLgbKSvytj8ZoXYZNh5AWxfu3TQ3Ywt6Ip39oV9rD5R0xXkqoTYy9sZDQPev00YiO2xzR5
  sendReceiptEmail: false
  signingSecret: whsec_WnDE7AhIaqQujOLz1d1GhUt1enPERv7k
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
