bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Internal Order Confirmation'
pdf: null
plainTextTemplatePath: ''
recipientType: custom
replyTo: null
senderAddress: null
senderName: null
store: 860f9494-ac4c-4585-a706-7d792745a4f9 # Primary Store
subject: 'New registration: {% for lineItem in order.lineItems %}{{ lineItem.description }}{% if loop.index < order.lineItems|length %}, {% endif %}{% endfor %}'
templatePath: shop/_private/receipt/index.twig
to: 'ascmsepa@gmail.com, hello@pixel-brick.com'
