bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Internal Order Confirmation'
plainTextTemplatePath: ''
recipientType: custom
replyTo: null
subject: 'New ASCM web order'
templatePath: shop/_private/receipt/index.twig
to: hello@pixel-brick.com
