bcc: null
cc: null
enabled: true
language: orderLanguage
name: 'Customer Confirmation'
pdf: null
plainTextTemplatePath: ''
recipientType: customer
replyTo: null
senderAddress: null
senderName: null
store: 860f9494-ac4c-4585-a706-7d792745a4f9 # Primary Store
subject: 'ASCM SEPA: Thanks for your order.'
templatePath: shop/_private/receipt/index.twig
to: null
