descriptionFormat: '{product.type.name} - {title}'
handle: cltd
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: 'CLTD Course'
productFieldLayouts:
  126526fc-e721-480c-8884-089dc5cb105a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 0096b5e0-a4f5-4617-b999-aa19d42dbb9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7770f387-2cf7-4513-a502-02ecbf4c01f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 2749a654-bed9-4514-a105-1524dcfc19b3
            userCondition: null
            warning: null
        name: Content
        uid: df423ccb-cbc3-4901-877a-448b5196311f
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'cltd/{slug}'
skuFormat: ''
variantFieldLayouts:
  5835060f-694f-41dc-8cef-67c50a908549:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 344b39e4-5bc0-4e98-a540-c0b2f4969d42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54257be2-6195-4cb4-9c6f-a3c967538237
        userCondition: null
variantTitleFormat: '{product.title}'
