descriptionFormat: '{product.title} - {title}'
handle: cltd
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'CLTD Course'
productFieldLayouts:
  91003b44-d6fd-47b7-a625-34454d9e2766:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 1e83ff73-fae9-4723-a9da-2cab0f25af6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Course Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b1ad665-c6c1-4124-9f22-e57bc28d1861
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a5ae57e-468f-4688-84d4-ea2608a3be1d # Course Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e0a110d-70db-41b3-9ec4-16e1c77b6308
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 258b0a61-741e-4c8d-a027-332038627f18
            userCondition: null
            warning: null
        name: Content
        uid: d2dd2181-35dd-44ed-814c-58f0478fcbf1
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'cltd/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
