descriptionFormat: '{product.title} - {title}'
handle: course
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Course
productFieldLayouts:
  077e10b1-afd4-4149-a04f-9c8b5f7c4706:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: a037bd3f-6d74-4d9b-9cde-913d2eceecba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Course Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24cb9b0f-28c6-49f4-b40f-6fe0b3b65378
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: a992e963-e250-42c6-ae2f-1932bfa29f3a
            userCondition: null
            warning: null
        name: Content
        uid: b27580b7-d7d4-4a7e-b5ce-13156fea7027
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'course/{slug}'
skuFormat: ''
variantFieldLayouts:
  084de9bc-4a65-4c7f-bde5-5f785983f8f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 4ca4b9cf-b3e4-416f-859c-73251a8b9dc6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85a68e0a-73d9-4c27-b53a-d5e78099df7e
        userCondition: null
variantTitleFormat: '{product.title}'
