descriptionFormat: '{product.type.name} - {title}'
handle: cscp
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'CSCP Course'
productFieldLayouts:
  fcc707c5-786c-4209-88d4-1053c74ac6d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: c5fa2204-7937-4dc4-9ab1-3a64ec0807fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12446c03-92a7-4663-8f0d-a490c3cab9c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 4cae1e01-fa91-4271-a216-638ef3ee3c5b
            userCondition: null
            warning: null
        name: Content
        uid: 29611b0d-47ec-4b67-878b-c28cb810df70
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'cscp/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
