descriptionFormat: '{product.title} - {title}'
handle: cscpCourse
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: true
name: 'CSCP Course'
productFieldLayouts:
  25935f0e-f2a2-4a0d-8661-baefe454da26:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: e0b51fbe-1540-4661-af7b-35e04d9e0864
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 31d0c503-9262-4371-b83d-ef5f89015cb1
            userCondition: null
            warning: null
        name: Content
        uid: cdf4d81f-5aba-42ac-b849-bbcfcc16e9f5
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'cscp-course/{slug}'
skuFormat: ''
variantFieldLayouts:
  2a3d9051-c34f-405a-88a4-36740084196f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: d06256fe-66bf-4568-91fd-662f9223ed4a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3492a76e-af33-400d-ae75-8322f13c634d
        userCondition: null
variantTitleFormat: '{product.title}'
