descriptionFormat: '{product.type.name} - {title}'
handle: ctsc
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'CTSC Course'
productFieldLayouts:
  a6a130c7-6bda-4264-8b03-5c0546cd6248:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 369f4de3-3629-4f72-ba8f-3011cd331bc5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a98f0e71-62a8-41d2-a574-1704c92f7b4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: ce7d25d4-b0c9-44ba-91a1-fba5e319b474
            userCondition: null
            warning: null
        name: Content
        uid: e06e6adb-5469-4022-b2a7-095acd05bbd8
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'ctsc/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
