descriptionFormat: '{product.title} - {title}'
handle: ctsc
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'CTSC Course'
productFieldLayouts:
  ab6ce148-4da6-4566-ac12-15fe5dfe00c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: ec370592-5d8e-424e-8f5c-90723f0e2d7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f688d7f-0844-47cb-aeb8-0881f003441c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 68b79b6a-bd16-447b-96ad-1ea94b9c6c44
            userCondition: null
            warning: null
        name: Master
        uid: ca860273-b16f-4f77-9111-8b697906d950
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'ctsc/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
