descriptionFormat: '{product.title} - {title}'
handle: ctsc
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'CTSC Course'
productFieldLayouts:
  89b3c019-2d14-4ee8-afd4-55076e50ed7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: cb356bff-79ed-486e-a63e-94f28f0688c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Course Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03c9af3c-469c-438c-88e2-76b80a0f17dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a5ae57e-468f-4688-84d4-ea2608a3be1d # Course Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deeb5900-e198-4a5a-a4c2-216ae5038a96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 1cad9c86-0d1a-4f49-bae2-5a738b5c0557
            userCondition: null
            warning: null
        name: Content
        uid: 3520f30d-cd53-4877-8959-b25160c2af91
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'ctsc/{slug}'
skuFormat: ''
variantTitleFormat: '{product.title}'
