descriptionFormat: '{product.title} - {title}'
handle: meetings
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Meeting
productFieldLayouts:
  43b1065e-bcdb-42b7-8048-463c9affedf3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 21513807-a4cc-4aac-87fe-67f798d15b3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96bab796-5961-4252-88c6-defd8eb06d47 # Meeting Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbe3e8ba-7274-42ce-9808-28afeca8a291
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c95b827-2482-43c5-be1e-2af7d1d4a019
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81c20ba-ef6a-4af9-a151-76676391b738 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 577f91e3-2dde-4b82-8d6f-c8cd89237f03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 983c95f8-bafc-4872-8e3a-4da48c387de1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 9f342dde-97d6-4901-94b0-0f8bea5b248b
            userCondition: null
            warning: null
        name: Content
        uid: cf92af4c-a738-4b6f-95ea-a812038abb26
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'meeting/{slug}'
skuFormat: ''
variantFieldLayouts:
  92688115-eab1-4504-8144-d7113a38ecc8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 8d1ae1d8-7a02-4c3d-a95d-9e9981879f69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d52ba219-6744-4675-9e06-585bacacbbe1
        userCondition: null
variantTitleFormat: '{product.title}'
