descriptionFormat: '{product.title}'
enableVersioning: false
handle: membership
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
maxVariants: null
name: Membership
productFieldLayouts:
  2780a01e-fb0c-4426-94ba-7a028ab68a2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T21:34:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: b7802877-b2d3-49b6-99f1-8350fded8975
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 14ff9552-ccfe-4cea-a92f-3c387836ed7f
            userCondition: null
            warning: null
        name: Content
        uid: 7d2014d8-ed99-4ae0-86cc-cefc74792fdc
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'membership/{slug}'
skuFormat: ''
variantFieldLayouts:
  55258978-d3db-4e06-884c-5fad18930a1e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T21:34:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 887dfa01-3f91-4767-a99b-768aa441ad82
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: SKU
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: ef49edb4-782b-4a30-a287-fcbfe749f519
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 67a1e343-4934-4c0b-bf87-b35ade576986
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Inventory
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 7c325e7a-610b-4b65-9c9d-4205e68eb177
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Available for purchase'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: de0cc647-8667-4762-9838-787d482008d3
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Allowed Qty'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 1544bba7-504a-4b43-b51b-f777f24d6e83
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Free Shipping'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: efd67f36-ce45-4f65-a3ec-b164d54d1b8c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Promotable
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: a3e468c5-a628-4baa-a393-03ce412d85e8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Dimensions
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 36fc9cff-bebb-48d6-8a27-22d1d8af8c35
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2024-08-19T21:34:45+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Weight
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: f8d744fa-4bf7-47b2-8a42-1a3a78453830
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a5626eb-fb41-4e67-ba3f-a5e51dc4a10e
        userCondition: null
variantTitleFormat: '{product.title}'
