descriptionFormat: '{product.title} - {title}'
handle: microCertifications
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
maxVariants: null
name: Micro-certifications
productFieldLayouts:
  e1ea0ca4-fea1-4b84-aad2-e8380262a40f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: f606a9ab-53d8-45dd-ace5-05716e58a69e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40887522-f291-4574-a00f-30d4a2aa4b00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: be2b33fa-cbe0-48d6-9925-17b5d75807d3
            userCondition: null
            warning: null
        name: Content
        uid: 77f00a42-0f44-410d-b3f3-d0b0d0eaaaab
        userCondition: null
productTitleFormat: ''
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ''
    uriFormat: 'micro-certifications/{slug}'
skuFormat: ''
variantFieldLayouts:
  4c888fbf-421c-46ae-b708-09a10b7ece18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: b804813a-cf3d-4990-b1cc-d6bab73bbed5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebe1547e-943b-4ef0-80b9-8b938790e285
        userCondition: null
variantTitleFormat: '{product.title}'
