field: 4e37e30d-d1e5-4f98-9181-e55cff026870 # Colleges
fieldLayouts:
  5bde8d1a-a0c8-421e-82f0-a0ec20608951:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1bde4bcb-f5ce-4123-99fb-6754cc9b43b1 # College Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae14a13e-bd4b-4155-a59b-6bf2ee475146
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c17098eb-0d3a-4365-8942-6910715a084d # College Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fe119dd-2263-4d3d-8c84-8ac4cf22f79c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3affc63b-0b69-4d19-bcb8-a7f34b74c8b9 # College Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0a073a1-19ef-4559-8e01-82ac17b6d19d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6144f22-ffe3-4e48-abcb-38cd098ed16a # College Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f88f003-25c8-4502-9fef-3d2a76316810
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2dcfaa4-a88c-4336-bbd9-03befa5876bf
        userCondition: null
fields:
  1bde4bcb-f5ce-4123-99fb-6754cc9b43b1: # College Name
    columnSuffix: homlwwwy
    contentColumnType: text
    fieldGroup: null
    handle: collegeName
    instructions: null
    name: 'College Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3affc63b-0b69-4d19-bcb8-a7f34b74c8b9: # College Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: collegePhoto
    instructions: null
    name: 'College Photo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:ce6a0c61-fef7-4b8b-b765-d687224a736c' # Colleges
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 0
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1d1cac83-523d-465d-95dd-f268196920aa' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:ce6a0c61-fef7-4b8b-b765-d687224a736c' # Colleges
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c6144f22-ffe3-4e48-abcb-38cd098ed16a: # College Page
    columnSuffix: earaoubf
    contentColumnType: string(255)
    fieldGroup: null
    handle: collegePage
    instructions: null
    name: 'College Page'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  c17098eb-0d3a-4365-8942-6910715a084d: # College Location
    columnSuffix: ewqgsgvh
    contentColumnType: text
    fieldGroup: null
    handle: collegeLocation
    instructions: null
    name: 'College Location'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: college
name: College
sortOrder: 1
