field: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
fieldLayouts:
  c0a28582-1bca-4e17-ba36-dc38f70e9311:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2da6c2a5-4de0-401f-bc54-ce4297dde71c # Event Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a28615c-238d-4439-9c7a-586d7869ca48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0beac817-3542-4192-820b-a18528b2c112 # Instructor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfd43571-4b8b-4a72-bca3-565e451244ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed3b8215-46bf-4312-aa8c-e6aad16de0e3
        userCondition: null
fields:
  0beac817-3542-4192-820b-a18528b2c112: # Instructor
    columnSuffix: ltulfhxi
    contentColumnType: text
    fieldGroup: null
    handle: instructor
    instructions: null
    name: Instructor
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2da6c2a5-4de0-401f-bc54-ce4297dde71c: # Event Date
    columnSuffix: mingrwxe
    contentColumnType: datetime
    fieldGroup: null
    handle: theEventDate
    instructions: null
    name: 'Event Date'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 15
      showDate: true
      showTime: true
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: eventDate
name: Date
sortOrder: 1
