field: 22da0d09-946b-40e6-98d3-e916a61eb1bc # Basic Form Fields
fieldLayouts:
  d344699c-3122-4432-af3c-c3b355f26832:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d802d0ac-8a9e-44e6-aa83-81058b4fec17 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0741f0f-735c-445e-bd5f-83f3affb5c87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de5551-859b-4e9b-85d5-6f6b35d66f25 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ce9274-6aa5-48e9-b398-6d5b863f30cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 179b6899-8e48-4cfc-af11-f067e37c05e1 # Min Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b992b0e0-2623-4d85-8f5f-9b0fe9285635
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5013b61-5507-4358-9aa0-c1e82a55bcef # Max Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c685a78-4909-4c9b-b70c-a21fdc7d2a27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd30d861-0062-4e1f-aa8a-fbf266cb7670 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62860455-c892-48e8-9059-eead08892dd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0252dfc9-e1b7-4250-8580-54166f2ecbf4
        userCondition: null
fields:
  97de5551-859b-4e9b-85d5-6f6b35d66f25: # Handle
    columnSuffix: xtvmrwru
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  179b6899-8e48-4cfc-af11-f067e37c05e1: # Min Value
    columnSuffix: esizjlyy
    contentColumnType: integer(10)
    fieldGroup: null
    handle: minValue
    instructions: null
    name: 'Min Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  d802d0ac-8a9e-44e6-aa83-81058b4fec17: # Label
    columnSuffix: qyvmxhjn
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  dd30d861-0062-4e1f-aa8a-fbf266cb7670: # Required
    columnSuffix: bdtbamul
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  e5013b61-5507-4358-9aa0-c1e82a55bcef: # Max Value
    columnSuffix: yzbhrqdh
    contentColumnType: integer(10)
    fieldGroup: null
    handle: maxValue
    instructions: null
    name: 'Max Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
handle: number
name: Number
sortOrder: 5
