field: 22da0d09-946b-40e6-98d3-e916a61eb1bc # Basic Form Fields
fieldLayouts:
  68a6fbb8-7433-40b1-846d-414b1d701833:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f0344042-acf5-4dff-8157-19000db65a42 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e4c1bc3-b84c-44da-a3f2-03d8a9958d00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16a2366c-f4ac-4bb2-b3ae-41f892c2604f # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9504c34a-681d-478c-af56-96756a4cea2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6f5353b9-17c2-4aea-98cb-00396a0cde55 # Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a11145f-e528-40e8-b6f8-94616f98cd65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f5ed2aa-c7fe-4060-a0af-b8458aabba35 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c2d2256-c6d6-4398-889b-63103e58971c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48efacfc-3b05-4144-9a25-86550536ebc3
        userCondition: null
fields:
  6f5353b9-17c2-4aea-98cb-00396a0cde55: # Placeholder
    columnSuffix: tyawvkap
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: null
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  8f5ed2aa-c7fe-4060-a0af-b8458aabba35: # Required
    columnSuffix: mhtslvye
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  16a2366c-f4ac-4bb2-b3ae-41f892c2604f: # Handle
    columnSuffix: glzarveh
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  f0344042-acf5-4dff-8157-19000db65a42: # Label
    columnSuffix: cgzihdon
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: singleLine
name: 'Single Line'
sortOrder: 1
