field: f4c73025-98bb-4443-a0a0-26825873890b # Add Plan
fieldLayouts:
  c1454fa4-9af5-49e7-9bf9-113aecde9429:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3d62bbe5-007a-4423-bde4-d3e0e97f5ad0 # Select Plan
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5e25688-f5a6-4b72-a8f0-344ddc145f17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: daa7a77a-16ff-437e-a72b-b64279d9f19f # Custom Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bf27c06-e9dc-4b00-bb08-2e521ede8182
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51456749-2b0c-4632-aef9-2fa9ec2acb05 # Setup Fee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e409b58-ca77-4dbc-ad90-bafdd02eee23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1ea8773-f164-4115-8efa-77a76d7396d1 # Default
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7d1200b-6a55-4eb3-866c-412dedde26de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b7475705-3687-461c-a46f-7e48781e4195
        userCondition: null
fields:
  3d62bbe5-007a-4423-bde4-d3e0e97f5ad0: # Select Plan
    columnSuffix: huomsmfr
    contentColumnType: string
    fieldGroup: null
    handle: selectPlan
    instructions: 'Can''t see your plans? Go to [Subscriptions](https://sepa-ascm-craft.ddev.site/admin/enupal-stripe/settings/subscriptions) and click on Refresh Plans'
    name: 'Select Plan'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Select Plan...'
            -
              - value
              - ''
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  51456749-2b0c-4632-aef9-2fa9ec2acb05: # Setup Fee
    columnSuffix: ruledjzn
    contentColumnType: 'decimal(12,2)'
    fieldGroup: null
    handle: setupFee
    instructions: 'Setup Fee for the first payment'
    name: 'Setup Fee'
    searchable: true
    settings:
      decimals: 2
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  daa7a77a-16ff-437e-a72b-b64279d9f19f: # Custom Label
    columnSuffix: mjsdlguz
    contentColumnType: text
    fieldGroup: null
    handle: customLabel
    instructions: 'Override the default text displayed for each plan (i.e. “Nickname amount/interval”)'
    name: 'Custom Label'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: 'Awesome Plan $35.00/month'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  f1ea8773-f164-4115-8efa-77a76d7396d1: # Default
    columnSuffix: atbjcurb
    contentColumnType: boolean
    fieldGroup: null
    handle: default
    instructions: 'Please make sure that just one default is enabled'
    name: Default
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
handle: subscriptionPlan
name: 'Subscription Plan'
sortOrder: 1
