field: d67f9d36-68d8-4636-96d7-de659da1911f
fieldLayouts:
  855737bb-9b53-4f92-9ff2-23d23ec83588:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3bae566b-3f12-44f8-8159-cf8441346dbc # Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ba4d18c-ebe3-4053-b263-496a40ec1b64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae5c7c6d-0501-49c9-bbb5-f9116db408b0 # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e702c269-d1c6-433f-9b9d-2831e7ceb1c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53fd8fb0-f108-439e-a47e-53a4bb06cee1
        userCondition: null
fields:
  3bae566b-3f12-44f8-8159-cf8441346dbc: # Name
    columnSuffix: deirkoom
    contentColumnType: text
    fieldGroup: null
    handle: variantName
    instructions: null
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: 'Size, Color, Version, etc..'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ae5c7c6d-0501-49c9-bbb5-f9116db408b0: # Options
    columnSuffix: odofkbtw
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: 'If Name is Size you can fill this table with: Small          small           10'
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add new option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - 40%
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Handle (Unique)'
                -
                  - handle
                  - handle
                -
                  - width
                  - 40%
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: 10
      minRows: 1
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: variants
name: 'Basic Variants'
sortOrder: 1
