eventFieldLayouts:
  8e9ec731-d655-449b-8d30-eddcfb367582:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: 2bcd156e-9c97-45f2-b919-07fe5a2155aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5960a2d9-5b7f-47ac-b5eb-d76f27c7ee93
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c44069f5-99f1-4d98-a622-689da546e37a
        userCondition: null
handle: cltd
hasTickets: true
hasTitleField: true
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: 'CLTD Course'
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: cltd/_event
    uriFormat: 'cltd/{slug}'
titleFormat: null
titleLabel: Title
