enableVersioning: false
eventFieldLayouts:
  314ccc2e-ec4f-4b09-aaf7-909badab73a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: sessions
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionsField
            uid: 610a05fd-77e0-4066-818b-2c74d1d6464a
            userCondition: null
            warning: null
          -
            attribute: ticketTypes
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypesField
            uid: c280b4cf-ff14-4929-ac03-050ecfb83b6d
            userCondition: null
            warning: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T17:23:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: 8aa3b4ed-c500-4830-b7cd-c986cae21238
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:25:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a89c4748-13d5-41ba-b2b9-46e4feba446e # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49e1ef7a-24a2-4de0-9c12-b8355276f0fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:23:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1587fa3-bc0c-4e9e-95e9-9e5cd9663f00
            userCondition: null
            warning: null
            width: 100
          -
            attribute: tickets
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketsField
            uid: 6828c6aa-f8bf-4b7c-9146-6e67c5d197c3
            userCondition: null
            warning: null
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: 86c9b848-1bdb-4483-9b1e-e585b466d63a
            userCondition: null
            warning: null
        name: Content
        uid: 46a40f7c-392a-4093-a3a4-23154b731bb5
        userCondition: null
handle: cscp
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: 'CSCP Course'
purchasedTicketTitleFormat: '{event.title} - {ticket.title}'
sessionFieldLayouts:
  85826e54-ee9f-403d-8426-74f03cc781ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: startDate
            dateAdded: '2025-07-02T03:32:08+00:00'
            defaultTime: null
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            showTimeZone: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionStartDateTimeField
            uid: 68d89a11-2483-44ed-81ba-7507295e391f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: endDate
            dateAdded: '2025-07-02T03:32:08+00:00'
            defaultTime: null
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            showTimeZone: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionEndDateTimeField
            uid: 86ac6d9e-1bac-4ac3-ba4d-cd31368f39d7
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allDay
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionAllDayField
            uid: 80efafeb-9429-4975-9fa6-ff974bfa7bbb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: frequency
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionFrequencyField
            uid: 276c1efe-fc83-4c6a-84fc-4ac98986e0eb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: a7cca675-f8c9-4228-aa4c-c2cb8b3f1a3a
            userCondition: null
            warning: null
        name: Content
        uid: f5a7b2a3-9835-42eb-96e5-b77451634837
        userCondition: null
sessionTitleFormat: '{dateSummary}'
shippingCategoryId: 1
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: cscp/_event
    uriFormat: 'cscp/{slug}'
taxCategoryId: 1
ticketFieldLayouts:
  0d61d380-72f5-43f0-87a7-46172533f755:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T03:32:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\TicketTypeTitleField
            uid: 66114503-3816-434f-82a1-1b1e25c7e107
            userCondition: null
            warning: null
            width: 100
          -
            attribute: capacity
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypeCapacityField
            uid: 2fe91f7b-02fe-4214-9baf-ec5df25c61e8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypePriceField
            uid: 5e692e29-875f-4004-9bbe-a6d98d3aaa22
            userCondition: null
            warning: null
            width: 100
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:08+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: 4018f486-1d27-49a0-867d-a59a96bec9e7
            userCondition: null
            warning: null
        name: Content
        uid: 7cf3fefc-b14d-47cf-9d24-6e3e69577fec
        userCondition: null
ticketSkuFormat: ''
ticketTitleFormat: '{type.title}'
