eventFieldLayouts:
  d107dd14-7199-4604-80e8-2257bad32fea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: af8d971d-a01d-4844-8e1c-e94d3595ede1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77e9090c-fb27-4e8e-9ab1-af5fc43db673
        userCondition: null
handle: ctsc
hasTickets: true
hasTitleField: true
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: 'CTSC Course'
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ctsc/_event
    uriFormat: 'ctsc/{slug}'
titleFormat: null
titleLabel: Title
