eventFieldLayouts:
  d107dd14-7199-4604-80e8-2257bad32fea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T17:24:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: af8d971d-a01d-4844-8e1c-e94d3595ede1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:25:26+00:00'
            elementCondition: null
            fieldUid: a89c4748-13d5-41ba-b2b9-46e4feba446e # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a955634-fe13-46a8-a191-3801895ecd38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:25:26+00:00'
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac7514cd-b267-4e42-9a0e-4bb694e7c891
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77e9090c-fb27-4e8e-9ab1-af5fc43db673
        userCondition: null
handle: ctsc
hasTickets: true
hasTitleField: true
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: 'CTSC Course'
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: ctsc/_event
    uriFormat: 'ctsc/{slug}'
titleFormat: null
titleLabel: Title
