enableVersioning: false
eventFieldLayouts:
  c4a70874-b57d-471c-9105-c5608fdaf516:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: sessions
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionsField
            uid: ec097754-f589-4773-a6f2-ec92b87bc062
            userCondition: null
            warning: null
          -
            attribute: ticketTypes
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypesField
            uid: 8b201450-3866-4090-bac0-c7e2373cb7d1
            userCondition: null
            warning: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T22:04:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: e3a8b08f-d2c8-4c1f-9170-6cfb2f6f1014
            userCondition: null
            warning: null
            width: 100
          -
            attribute: tickets
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketsField
            uid: d151e757-eada-43eb-ba5f-eab6caf4a4e2
            userCondition: null
            warning: null
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: 96f7a730-e7e2-4860-a2eb-3843caaffa46
            userCondition: null
            warning: null
        name: Content
        uid: 9b24ef53-28e8-4919-8e5d-78e012a409ea
        userCondition: null
handle: foscm
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: FOSCM
purchasedTicketTitleFormat: '{event.title} - {ticket.title}'
sessionFieldLayouts:
  e78b5cdb-c60c-4787-8e45-19109f2d6687:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: startDate
            dateAdded: '2025-07-02T03:32:19+00:00'
            defaultTime: null
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            showTimeZone: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionStartDateTimeField
            uid: be48da89-b4a0-45a3-a830-8a445fcbbbeb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: endDate
            dateAdded: '2025-07-02T03:32:19+00:00'
            defaultTime: null
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            showTimeZone: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionEndDateTimeField
            uid: 51a09bf8-eb45-4afe-9d1c-be638f10fa69
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allDay
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionAllDayField
            uid: 8c6a5a36-3d07-482f-8d79-9c838adfc9ba
            userCondition: null
            warning: null
            width: 100
          -
            attribute: frequency
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\SessionFrequencyField
            uid: 19d6f3c7-b650-4726-a898-391f83b1f2a2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: 19dcd4a8-6141-4b31-928a-f59beb5ad658
            userCondition: null
            warning: null
        name: Content
        uid: 02e33d19-ceec-4ba2-8d6a-619c088fefa3
        userCondition: null
sessionTitleFormat: '{dateSummary}'
shippingCategoryId: 1
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: foscm/_event
    uriFormat: 'foscm/{slug}'
taxCategoryId: 1
ticketFieldLayouts:
  14553b13-87d4-4387-804c-007f3145f808:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T03:32:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\TicketTypeTitleField
            uid: 2abe351e-74f3-42b7-a14a-8bebe6315f08
            userCondition: null
            warning: null
            width: 100
          -
            attribute: capacity
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypeCapacityField
            uid: 8431e43b-970d-4f79-96b8-fb57d005e69f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\TicketTypePriceField
            uid: 7d2e5afb-2cd2-46a9-aa58-29995fd2a0b1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: purchasedTickets
            dateAdded: '2025-07-02T03:32:19+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: verbb\events\fieldlayoutelements\PurchasedTicketsField
            uid: 11f74013-afee-45cf-b6ed-63c9f2150eda
            userCondition: null
            warning: null
        name: Content
        uid: 026ed448-2d30-4715-92c7-fe122541dcf7
        userCondition: null
ticketSkuFormat: ''
ticketTitleFormat: '{type.title}'
