eventFieldLayouts:
  d913408a-dd8b-4839-aff3-9e994899abdf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T17:24:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: verbb\events\fieldlayoutelements\EventTitleField
            uid: 56baabfe-6785-43ac-b6cf-6bc478c79e12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:25:44+00:00'
            elementCondition: null
            fieldUid: a89c4748-13d5-41ba-b2b9-46e4feba446e # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4954f2c7-df72-4294-a781-4839449b9258
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:25:44+00:00'
            elementCondition: null
            fieldUid: d580aec8-08d7-421b-9280-b4a7459f684b # Event Dates
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 821d40b9-2500-4b61-91d7-c0259df0f99f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0621fccb-1c65-4e2f-9d30-95beaefefc04
        userCondition: null
handle: microcertifications
hasTickets: true
hasTitleField: true
icsDescriptionFieldHandle: ''
icsLocationFieldHandle: ''
icsTimezone: ''
name: Microcertifications
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: microcertifications/_event
    uriFormat: 'microcertifications/{slug}'
titleFormat: null
titleLabel: Title
