fieldLayouts:
  4784fef3-5c31-4351-b28d-5f717234cea1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 944455b3-0a1e-4223-8110-a9a5d272f6b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73578354-c792-4f1a-942d-271dc4715c4c # Article Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9094c7a-c2cd-48c0-a41e-4cc8d499c87e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38ab0050-d304-44cd-8737-ab3d7136a645 # Inset Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7248d9d-7c1c-4e4b-9fe7-18eab6a86be4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81c20ba-ef6a-4af9-a151-76676391b738 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ce0a71a-c6df-4131-8c93-9270d6913f37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ba6d09f-8d1e-4c65-91f9-35b77e080b4a # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fef59029-b8a6-4acd-bff9-5f04cc75d506
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3d970a4-9bc6-4132-958d-5f5443024532
        userCondition: null
handle: articles
hasTitleField: true
name: Articles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
