color: null
fieldLayouts:
  84278f94-4d2f-43d6-bbc8-2d14fb5633ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5cb9abe-21ca-4274-8128-8a1565d7b476
            handle: null
            includeInCards: true
            instructions: null
            label: Name
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fca8cafc-33ba-451a-80c4-3777b6084ffe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebea49c4-f0cb-43c5-9c43-e0a7229319db
            handle: null
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3005a373-ee92-4038-a880-202cdc1dd6d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46995c3e-2705-448e-9959-bc44abdced57
            handle: null
            includeInCards: false
            instructions: null
            label: Headshot
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5697e185-a0f2-4548-b6cb-21e02ecec413
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac32b609-961c-4607-9f0a-3a60d6f9fb7a
            handle: null
            includeInCards: false
            instructions: null
            label: 'LinkedIn URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c7cb289-9e14-4226-8d9c-9db43349d0c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c42ba01-a0b7-4d2a-b9f8-84bedb2b5f91
        userCondition: null
handle: boardMember
hasTitleField: false
icon: null
name: 'Board Member'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
