fieldLayouts:
  b20e3b00-84ba-4506-b05d-0089295fd898:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9297e07a-5678-458d-b143-c0fd078cab73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f035222-2a22-4da2-842a-ee4bf1b36bde # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27dbad68-cccc-4cfc-9b97-ee12d44bc330
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0429613c-3583-4760-85b5-ba84127be96a
        userCondition: null
handle: bylaws
hasTitleField: false
name: Bylaws
section: 339e05fa-565f-4fa4-98ad-05cc58243fb8 # Bylaws
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
