fieldLayouts:
  3412ef88-6c5f-48b9-856d-fc4f8b309dc6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0b12a19e-71d6-4728-baf4-35604c089287
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eccf683d-f213-49de-841a-1834609cd122
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17545c21-9a88-4805-a223-c771d695e3b4 # College Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee1504de-7a1c-4620-91ac-e9f207817058
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e37e30d-d1e5-4f98-9181-e55cff026870 # College Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8f2d36e-5a66-4922-a929-9d98ff1c3703
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af42fc91-6645-4eb5-b738-5798ede1a57e # College Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6234c48-4047-473b-9c63-85198abd64aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d028c1f-dc78-4cc5-bbb7-25a0f47a90ab # College Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4cdebc5-29e6-4b54-92f2-5ff09502ac81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbcdeff7-1fe8-429b-b47c-34a269db0479 # Board Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 743d6875-d106-48ab-b935-181f76f43c74
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 334c6606-0429-4e59-aa2c-cdd1ba70a28a
        userCondition: null
handle: college
hasTitleField: true
name: College
section: 4f19a1cf-7acb-4101-bea3-edea33a0ccf5 # Colleges
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
