fieldLayouts:
  97f32519-e4fb-49f0-88fb-1b213489f287:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 089a1c3c-0b79-4254-bdbf-3eea76a4e5f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a18d61d1-ff0c-426f-9fbb-6c9cef4ebf92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c8745c7-b128-4813-8b9e-19a93f83984d # Opportunity Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d29972b9-caa2-4ba5-8e6e-9dd79727d199
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77174520-99b3-46fa-a19a-157ce298f60e # Submission Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65c19391-85f5-436a-93ab-8525694ad37a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4bc88bcb-2668-499d-8746-9fd678054281
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 10bc5384-4844-49dc-b8f1-948bbb791731 # Opportunities
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
