color: null
fieldLayouts:
  e61d8f21-7578-4c52-a264-4dd650cf6d22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1e464d3f-95fc-43bb-8928-c6aea9182bf3
            handle: label
            includeInCards: true
            instructions: null
            label: Label
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa07786-99e4-47c2-8723-2018f9daac3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 019c9c67-ec74-4f61-9edf-6806fdd89dab
            handle: fieldHandle
            includeInCards: false
            instructions: null
            label: Handle
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd378edf-2a3f-405b-abe3-b3a62fa6436c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2b26d63-6ed5-4b5b-bf85-fd1078ef4742
            handle: options
            includeInCards: false
            instructions: null
            label: Options
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 720df87e-b8a3-444b-8c60-3d31fa28bb99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da3f1f08-83a3-447d-8f6d-019322810442
            handle: required
            includeInCards: false
            instructions: null
            label: Required
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 828efc01-3cd7-47be-a8a0-820bfe8152ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 978e4b5a-1f0c-4f69-bb51-2c5598318021
        userCondition: null
handle: dropdown
hasTitleField: false
icon: null
name: Dropdown
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
