color: null
fieldLayouts:
  851be6f9-2772-48df-a858-3e184688fe5c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-02T01:33:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 511ad373-a228-4663-ab92-00990d5cc183
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-02T01:34:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c501c3c9-4eb1-4c1e-ba93-7f69a515d72a # Calendar PDF
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 948140ae-f8f7-474a-be86-0fe3f8fb0c66
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f10c5230-b9e7-4abb-828a-dfa9a011bf9f
        userCondition: null
handle: education
hasTitleField: true
icon: null
name: Education
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
