color: null
fieldLayouts:
  4b28817d-e4b4-4d1d-b78a-e15bd175865b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5926ddee-0554-44d0-b20f-c08935836767
            handle: label
            includeInCards: true
            instructions: null
            label: Handle
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fae87f69-2aa0-493b-ba85-f1011de6eadb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cab4b19-208b-4ef5-8639-399ccb9a1c52
            handle: null
            includeInCards: false
            instructions: null
            label: 'Hidden Value'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56da079f-23c2-430e-80b2-870fbc7bc29a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30a807ed-2bd4-460b-a4e7-7d32bc677eb3
        userCondition: null
handle: hidden
hasTitleField: false
icon: null
name: Hidden
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
