fieldLayouts:
  32a5eb09-5639-4066-b7bb-e954d8cbc756:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0bb108a-e3c3-4986-8a04-7f32296259c6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a36e14be-04b2-4c6f-97b1-46e878871064
        userCondition: null
handle: home
hasTitleField: false
name: Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
