color: null
fieldLayouts:
  780808f7-2a81-4068-9ce7-67780328f4e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af02a4d6-3881-482f-ba11-4b1630a67c06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96bab796-5961-4252-88c6-defd8eb06d47 # Meeting Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2824c5ef-e205-452b-91d9-b7224dcd3859
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e62e962-beab-4351-ac61-c273c0acc9cc # Meeting Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 617d9405-33ac-4c8c-ac85-7f7e8bdb1d83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5dc608b2-0088-4005-b1e1-88ff0ad17f95 # Meeting Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f50dc89-6444-4653-a8d2-6507c436d0b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3f05c1e-f9b6-4657-9695-4c0ecdf3be48 # Meeting Feature Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9bb5eb7-f9a3-422d-87f0-a0d5e15cd1b4
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 899d4f06-a985-4935-885a-2fa0ca005252
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 846c5a6a-33a2-442b-8bc8-2f8b49f47ea0 # Meeting Registration Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cf00281-67f1-40e6-a373-d2c2787eef8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 636bd5bf-6e10-4629-9034-5517fbd47346 # Meeting Details Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a6c8840-dc4e-4b18-aa8e-4041a097d1b8
            userCondition: null
            warning: null
            width: 100
        name: Registration
        uid: 4c1da1eb-467b-4f2a-a938-89ad77e42019
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4ba6d09f-8d1e-4c65-91f9-35b77e080b4a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ed52a40-1087-4205-a6a2-933d930e9828
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fae24e8a-6aa9-455e-88f0-64d79cdc5f80 # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 890fcd10-7e92-4e8f-a7bf-49c5a7badcb4
            userCondition: null
            warning: null
            width: 100
        name: 'Meeting Recap'
        uid: a0971ca1-62d4-4eba-b3d9-94859bc76168
        userCondition: null
handle: meetings_default
hasTitleField: true
icon: ''
name: 'Meetings - Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
