color: null
fieldLayouts:
  d344699c-3122-4432-af3c-c3b355f26832:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d802d0ac-8a9e-44e6-aa83-81058b4fec17
            handle: null
            includeInCards: true
            instructions: null
            label: Label
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0741f0f-735c-445e-bd5f-83f3affb5c87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97de5551-859b-4e9b-85d5-6f6b35d66f25
            handle: null
            includeInCards: false
            instructions: null
            label: Handle
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6ce9274-6aa5-48e9-b398-6d5b863f30cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 179b6899-8e48-4cfc-af11-f067e37c05e1
            handle: null
            includeInCards: false
            instructions: null
            label: 'Min Value'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b992b0e0-2623-4d85-8f5f-9b0fe9285635
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5013b61-5507-4358-9aa0-c1e82a55bcef
            handle: null
            includeInCards: false
            instructions: null
            label: 'Max Value'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c685a78-4909-4c9b-b70c-a21fdc7d2a27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd30d861-0062-4e1f-aa8a-fbf266cb7670
            handle: null
            includeInCards: false
            instructions: null
            label: Required
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62860455-c892-48e8-9059-eead08892dd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0252dfc9-e1b7-4250-8580-54166f2ecbf4
        userCondition: null
handle: number
hasTitleField: false
icon: null
name: Number
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
