color: null
fieldLayouts:
  3c0a6dd5-fa87-4892-b299-9741c4a56544:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c9bc5389-1f49-4f7a-b48a-0a3a05266994
            handle: label
            includeInCards: true
            instructions: null
            label: Label
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80d1ffdd-44de-408e-934a-09451979b3b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e3db193-91c6-4b22-88b9-1b6af80c542b
            handle: fieldHandle
            includeInCards: false
            instructions: null
            label: Handle
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9092e6b5-c3af-42c1-bbb4-43dce6fdf48d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1b0803c-fddc-416d-a44c-c78de2183bab
            handle: null
            includeInCards: false
            instructions: null
            label: Options
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9e2ad73-3be6-4bc8-8707-dcd242814800
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 578c31ba-d443-4d10-8c1a-c543aa9ded43
            handle: required
            includeInCards: false
            instructions: null
            label: Required
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06034cfe-cda2-4e88-8fc9-bcf2060f6583
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f11add9-a7a5-4284-bdad-2a86224aeb6b
        userCondition: null
handle: radioButtons
hasTitleField: false
icon: null
name: 'Radio Buttons'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
