fieldLayouts:
  605ba0d7-1fb3-417a-882b-b157d27618ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5da03c86-a8cf-422a-84bb-9f35854c8beb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a89c4748-13d5-41ba-b2b9-46e4feba446e # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06bfe5d5-3c9f-4500-aaef-d241555fe3d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c37ded9b-6848-41c3-a403-936821c0bc02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81c20ba-ef6a-4af9-a151-76676391b738 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5853b9e1-ab1c-488e-a985-1f14ef077089
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf93a59d-3112-46b5-a6cb-28b7de958bab
        userCondition: null
handle: scholarships
hasTitleField: true
name: Scholarships
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
