fieldLayouts:
  911e5457-5b04-4bc6-aaec-9bc6a7664729:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f04faee-5241-4e5e-821b-f6867827c8fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e37e30d-d1e5-4f98-9181-e55cff026870 # Colleges
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5dfc48c-6392-460a-b3e3-d623c6c19f2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4db825a8-f06d-467d-a950-1c8a2ab3ab3d
        userCondition: null
handle: students
hasTitleField: false
name: Students
section: 4f19a1cf-7acb-4101-bea3-edea33a0ccf5 # Students
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
