fieldLayouts:
  b16d4cae-59cf-4a4a-9489-70fd503fb860:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 492a3600-5bd1-4853-8c3d-ac602df3cd5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbcdeff7-1fe8-429b-b47c-34a269db0479 # Board Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b16a92b-2a57-444e-93ed-5bd0d6458cad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44a50d46-1952-4f50-9888-a0451201f968
        userCondition: null
handle: templeUniversity
hasTitleField: false
name: 'Temple University'
section: cbb35041-e529-42dd-8d49-897068042d05 # Temple University
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
