defaultPlacement: end
fieldLayouts:
  ce090cc9-0cf1-4bf9-ab45-083d63b96c50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 57618ef4-9984-4a0e-90bd-f04ced2113b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e969aae4-5ce3-496f-b4de-ea815828e23a
        userCondition: null
handle: articleTypes
name: 'Article Types'
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    hasUrls: true
    template: null
    uriFormat: 'article-types/{slug}'
structure:
  maxLevels: 1
  uid: 17d85dac-3573-4977-ace7-169f6c3ee86e
