baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'ASCM Southeastern Pennsylvania'
primary: true
siteGroup: 99bd89d9-407f-438f-805b-c28668a036b9 # ASCM Southeastern Pennsylvania
sortOrder: 1
