baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'ASCM Southeastern Pennsylvania'
primary: true
siteGroup: 432ea19b-8c63-4601-b4d9-bd1c4f6a4856 # ASCM Southeastern Pennsylvania
sortOrder: 1
