tabs:
  -
    elementCondition: null
    elements:
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: 1ac3fce4-9137-439d-9973-667cf0ef2892
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: __blank__
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: ebd8e1cd-bf0c-4f24-ab70-3c155e426454
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: a442fec6-9689-413d-a5ed-310aec304b80
        userCondition: null
        width: 100
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 1de24cfb-602f-4d4c-ad5c-32266ad4bc21
        userCondition: null
      -
        elementCondition: null
        fieldUid: 416e052a-ff8b-49b7-a84b-fc71a488e4ec # Company
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 3df87aee-7813-4878-ac84-33f326756f4b
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 420cc52f-a056-4c9d-8c2e-6cb98c17fc65 # Job Title
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 79d3f247-a0ed-4f39-99bb-abf9c1bbee91
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        type: craft\fieldlayoutelements\HorizontalRule
        uid: 8e80ec81-0e9e-4ff3-8d02-4c809e1a461a
        userCondition: null
      -
        elementCondition: null
        fieldUid: 7ab520da-9a2c-4dea-8176-b40f65e79334 # ASCM Member ID
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 7bee0e85-5f66-400b-8a86-2dc6d46a3cde
        userCondition: null
        warning: null
        width: 50
    name: 'Primary Info'
    uid: 6d7bcc45-f46b-45a3-8703-5c7e129e0e65
    userCondition: null
