fieldLayouts:
  8025c830-465c-4ad5-b570-9556badad8f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 547f0a70-be45-46dd-833a-03b9738c206e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c328cad7-ce1c-40ed-bc6b-7c04780b054e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ad8d382-7348-4697-9fc0-0ddcd8eedbdc
        userCondition: null
fs: courses
handle: courses
name: Courses
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: courses
transformSubpath: ''
