columnSuffix: rttdawgy
contentColumnType: datetime
fieldGroup: 7bece7ac-8980-4ae8-b101-0cd452924c69 # Users
handle: ascmMemberExpiration
instructions: null
name: 'ASCM Member Expiration'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
