columnSuffix: uxljbdxk
contentColumnType: boolean
handle: ascmMemberSuspension
instructions: null
name: 'ASCM Member Suspension'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: Suspended
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
