columnSuffix: tsbmntlr
contentColumnType: datetime
handle: ascmMemberJoin
instructions: null
name: 'ASCM Member Join'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
