columnSuffix: sidxxcla
contentColumnType: boolean
fieldGroup: 7bece7ac-8980-4ae8-b101-0cd452924c69 # Users
handle: ascmMemberPending
instructions: null
name: 'ASCM Member Pending'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: Pending
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
