columnSuffix: null
contentColumnType: integer(10)
handle: ascmMembershipId
instructions: null
name: 'ASCM Member ID'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
