columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 7bece7ac-8980-4ae8-b101-0cd452924c69 # Users
handle: ascmMembershipId
instructions: null
name: 'ASCM Member ID'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
