columnSuffix: null
contentColumnType: string
fieldGroup: 2f5d7ffc-4d16-47d1-a440-318d7f4ea068 # Common
handle: boardMembers
instructions: null
name: 'Board Members'
searchable: false
settings:
  contentTable: '{{%matrixcontent_boardmembers}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
