columnSuffix: ivxigorc
contentColumnType: text
fieldGroup: 2f5d7ffc-4d16-47d1-a440-318d7f4ea068 # Common
handle: collegeDescription
instructions: null
name: 'College Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
