columnSuffix: jsyhtmrh
contentColumnType: string
fieldGroup: 7bece7ac-8980-4ae8-b101-0cd452924c69 # Users
handle: country
instructions: null
name: Country
searchable: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Country
