columnSuffix: null
contentColumnType: string(27)
handle: courseRegistrationType
instructions: null
name: 'Course Registration Type'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - 'Learning System'
        -
          - value
          - learningSystem
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Exam
        -
          - value
          - exam
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Learning System + 2 Exam Vouchers'
        -
          - value
          - learningSystem2ExamVouchers
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
