columnSuffix: null
contentColumnType: string
handle: courseCalendar
instructions: null
name: 'Course Calendar'
searchable: false
settings:
  entryTypes:
    - 4c820bb6-573a-43e8-81cf-5c164dee9f17
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
