columnSuffix: null
contentColumnType: text
fieldGroup: a6fda9ad-6baa-4e9a-a498-51e13db75bb4 # Courses
handle: courseDescription
instructions: null
name: 'Course Description'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: e3f3b2e7-74dd-4b61-bb34-6b6c1db021a6 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
