columnSuffix: iyaidiho
handle: courseTitle
instructions: null
name: 'Course Calendar - Courses - Course Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
