columnSuffix: mjsdlguz
handle: customLabel
instructions: 'Override the default text displayed for each plan (i.e. “Nickname amount/interval”)'
name: 'Add Plan - Subscription Plan - Custom Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Awesome Plan $35.00/month'
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
