columnSuffix: null
contentColumnType: text
fieldGroup: bd4c0abb-c118-494a-bfea-68abdd8272a5 # Opportunities
handle: description
instructions: null
name: Description
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: e3f3b2e7-74dd-4b61-bb34-6b6c1db021a6 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
