columnSuffix: null
contentColumnType: string
handle: eventDates
instructions: null
name: 'Event Dates'
searchable: false
settings:
  entryTypes:
    - aacbb6c8-3f3b-4441-9505-3ad15f285f59
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
