columnSuffix: null
contentColumnType: string
fieldGroup: a6fda9ad-6baa-4e9a-a498-51e13db75bb4 # Courses
handle: eventDates
instructions: null
name: 'Event Dates'
searchable: false
settings:
  contentTable: '{{%matrixcontent_eventdates}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
