columnSuffix: hbvzrpki
handle: hiddenValue
instructions: 'You can use twig code'
name: 'Basic Form Fields - Hidden - Hidden Value'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: '{{ craft.request.path }}'
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
