columnSuffix: wzyrfcmc
handle: label2
instructions: 'This field will not visible in the form, just in the source code'
name: 'Basic Form Fields - Hidden - Handle'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
