columnSuffix: yzbhrqdh
handle: maxValue
instructions: null
name: 'Basic Form Fields - Number - Max Value'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: null
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Number
