columnSuffix: glfisaby
contentColumnType:
  - 'date:datetime'
  - 'tz:string'
handle: meetingDate
instructions: null
name: 'Meeting Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
