columnSuffix: qymnzwyn
contentColumnType: string(255)
handle: meetingRegLink
instructions: null
name: 'Meeting Registration Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
