columnSuffix: jyvgfxyg
contentColumnType: string(255)
fieldGroup: 2f5d7ffc-4d16-47d1-a440-318d7f4ea068 # Common
handle: meetingDetailsLink
instructions: null
name: 'Meeting Details Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
