columnSuffix: dzwcukry
contentColumnType: string(9)
fieldGroup: 2f5d7ffc-4d16-47d1-a440-318d7f4ea068 # Common
handle: memberStatus
instructions: null
name: 'Member Status'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Member
        -
          - value
          - member
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Non-member
        -
          - value
          - nonMember
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Student
        -
          - value
          - student
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
