columnSuffix: null
handle: multipleDates
instructions: null
name: 'Multiple Dates'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
