columnSuffix: eplapsbm
contentColumnType: string(20)
handle: prefix
instructions: null
name: Prefix
searchable: false
settings:
  byteLimit: null
  charLimit: 5
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
