columnSuffix: xbrcssqs
contentColumnType: string
fieldGroup: 7bece7ac-8980-4ae8-b101-0cd452924c69 # Users
handle: primaryEmail
instructions: null
name: 'Primary Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
