columnSuffix: wptqjwuy
handle: required6
instructions: 'This field is required?'
name: 'Basic Form Fields - Paragraph - Required'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
