columnSuffix: mhtslvye
handle: required3
instructions: 'This field is required?'
name: 'Basic Form Fields - Single Line - Required'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
