columnSuffix: bhjzmxxl
contentColumnType: text
handle: secondaryAddressLine1
instructions: null
name: 'Secondary Address Line 1'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
