columnSuffix: kugjwqvb
contentColumnType: string
handle: secondaryEmail
instructions: null
name: 'Secondary Email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
