columnSuffix: huomsmfr
handle: selectPlan
instructions: "Can't see your plans? Go to [Subscriptions](https://sepa-ascm-craft.ddev.site/admin/enupal-stripe/settings/subscriptions) and click on Refresh Plans"
name: 'Add Plan - Subscription Plan - Select Plan'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Select Plan...'
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
