columnSuffix: ismbaxow
contentColumnType: string(40)
handle: suffix
instructions: null
name: Suffix
searchable: false
settings:
  byteLimit: null
  charLimit: 10
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
