columnSuffix: null
contentColumnType: text
fieldGroup: 2f5d7ffc-4d16-47d1-a440-318d7f4ea068 # Common
handle: summary
instructions: null
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
