columnSuffix: mingrwxe
handle: theEventDate
instructions: null
name: 'Event Dates - Date - Event Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
