dateModified: 1751073935
email:
  fromEmail: ryan@pixel-brick.com
  fromName: 'ASCM Southeastern Pennsylvania'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    432ea19b-8c63-4601-b4d9-bd1c4f6a4856: 'ASCM Southeastern Pennsylvania' # ASCM Southeastern Pennsylvania
    aaad1390-39af-4043-be9b-1133437b5f8a: 'ASCM Southeastern Pennsylvania' # ASCM Southeastern Pennsylvania
system:
  edition: solo
  live: true
  name: 'ASCM Southeastern Pennsylvania'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
