changedFieldIndicator: 270674308
field: d580aec8-08d7-421b-9280-b4a7459f684b # Course Dates
fieldLayouts:
  2b78eb9e-99dd-4309-9355-bf020cc6cfde:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4cd3e737-8e35-454d-bd2f-dc47d9a9e6c4 # Course Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d0ad095-1541-4976-a1a7-2ef1da810484
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0d90c2e-fe1d-4254-8618-9d531c1a140c # Instructor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f4ea957-8543-4c17-86f4-85cc376b44ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cad46a0c-2bcd-4b7e-9a3c-5e34ed2c6eff
        userCondition: null
fields:
  4cd3e737-8e35-454d-bd2f-dc47d9a9e6c4: # Course Date
    columnSuffix: jxjikeeq
    contentColumnType:
      - 'date:datetime'
      - 'tz:string'
    fieldGroup: null
    handle: courseDate
    instructions: null
    name: 'Course Date'
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 30
      showDate: true
      showTime: true
      showTimeZone: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  e0d90c2e-fe1d-4254-8618-9d531c1a140c: # Instructor
    columnSuffix: fzgzitlq
    contentColumnType: text
    fieldGroup: null
    handle: instructor
    instructions: null
    name: Instructor
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
