fieldLayouts:
  808f388c-f3ab-49e1-8930-3addf3157404:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 376a58b1-c5bf-44fc-a7ef-663fc2ad705e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81c20ba-ef6a-4af9-a151-76676391b738 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1132e14-6df6-4949-8023-751347cdc3c8
            userCondition: null
            warning: null
            width: 100
        name: Master
        uid: 0596ac21-70b0-4327-a96f-7de5c69f489e
        userCondition: null
handle: aboutAscmSepa
name: 'About ASCM SEPA'
sortOrder: 2
