fieldLayouts:
  65e2e4c0-715f-4ab6-bfb4-a5659d8dc88f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 84f2482a-8b1d-4ca1-9b76-f80674db009a # Featured Products
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 008b480c-6aa4-4cd2-b8e6-d83540d564fd
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 39cda73b-9b63-4ac0-b244-166f3d528845
        userCondition: null
handle: homepageFeatureItems
name: 'Homepage Feature Items'
sortOrder: 7
