fieldLayouts:
  271c26f3-789a-4c90-bf3c-8d05f704ec90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0002e9f1-02b1-4d7d-af54-ce03d4249aea # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9654630f-b4b6-4191-931e-746eaf928272
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81c20ba-ef6a-4af9-a151-76676391b738 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee3eaedf-9b76-49c7-a530-8ec0aa107a4e
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 9b3d3ae6-42f0-4a92-bee4-87b45459b22c
        userCondition: null
handle: students
name: Students
sortOrder: 5
