defaultPlacement: end
enableVersioning: true
entryTypes:
  - 746a0ab8-83d0-4a8e-a2f6-2d0697922a0d # Articles
handle: articles
maxAuthors: 1
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - /articles
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: articles/_entry.twig
    uriFormat: 'articles/{slug}'
type: channel
