defaultPlacement: end
enableVersioning: true
handle: bylaws
name: Bylaws
propagationMethod: all
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: bylaws.twig
    uriFormat: bylaws
type: single
