defaultPlacement: end
enableVersioning: true
entryTypes:
  - 150077d3-2f72-4b4e-bf25-7dae5415f67b # Default
handle: opportunities
name: Opportunities
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: opportunities/_entry
    uriFormat: 'opportunities/{slug}'
type: channel
