defaultPlacement: end
enableVersioning: true
entryTypes:
  - 53bdf7bf-5079-4837-b63c-1c842aa68784 # College
handle: students
maxAuthors: 1
name: Colleges
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - /students
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  246ac9e2-0535-4ba5-b543-66b2eb9d969f: # ASCM Southeastern Pennsylvania
    enabledByDefault: true
    hasUrls: true
    template: students/_entry
    uriFormat: 'students/{slug}'
structure:
  maxLevels: null
  uid: fa2a46d9-52f7-4e06-9f75-718b0204c329
type: structure
